"""Builds a shareable HTML report of the network and what's blocked."""
import html
from datetime import datetime

from . import control


def build_html(result) -> str:
    nid = result.network_id
    rows = []
    for dev in result.devices:
        info = control.device(nid, dev.mac)
        name = info["label"] or (dev.name or dev.maker or ("Router" if dev.router else "Unknown device"))
        who = "This PC" if dev.this_pc else ("Router" if dev.router else info["profile"].title())
        state = "Paused" if info["paused"] else "Online"
        rows.append(f"<tr><td>{html.escape(name)}</td><td>{html.escape(who)}</td>"
                    f"<td>{html.escape(dev.ip)}</td><td class=mac>{html.escape(dev.mac.upper())}</td>"
                    f"<td class={'p' if info['paused'] else 'o'}>{state}</td></tr>")
    conf = control.net_config(nid)[1]
    blocked = ", ".join(conf.get("categories", []) + conf.get("sites", [])) or "nothing"
    when = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    return f"""<!doctype html><html><head><meta charset=utf-8>
<title>Home Network report</title>
<style>
 body{{font-family:Segoe UI,system-ui,sans-serif;background:#0a0f1c;color:#e9eef8;margin:0;padding:40px}}
 .wrap{{max-width:820px;margin:0 auto}}
 h1{{font-size:26px;margin:0 0 4px}} .sub{{color:#8793aa;margin-bottom:24px}}
 .card{{background:#121a2b;border:1px solid #1f2b43;border-radius:14px;padding:20px;margin-bottom:18px}}
 table{{width:100%;border-collapse:collapse;font-size:14px}}
 th,td{{text-align:left;padding:10px 8px;border-bottom:1px solid #1f2b43}}
 th{{color:#8793aa;font-size:12px;text-transform:uppercase;letter-spacing:.04em}}
 .mac{{font-family:Consolas,monospace;color:#8793aa}} .o{{color:#22c55e}} .p{{color:#f5a524}}
 .pill{{display:inline-block;background:#192439;border-radius:20px;padding:4px 12px;margin:2px}}
</style></head><body><div class=wrap>
 <h1>Home Network report</h1>
 <div class=sub>{html.escape(result.network)} · router {html.escape(result.gateway)} · {when}</div>
 <div class=card><strong>{len(result.devices)} devices</strong>
 <table><tr><th>Device</th><th>Belongs to</th><th>IP</th><th>MAC</th><th>Status</th></tr>
 {''.join(rows)}</table></div>
 <div class=card><strong>Website blocking</strong><br><br>Blocked: {html.escape(blocked)}</div>
 <div class=sub style="margin-top:24px">Generated by Home Network Manager · your own network only</div>
</div></body></html>"""


def save(result, path: str) -> str:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(build_html(result))
    return path
